### ISSUE TITLE
Realpath isn't installed by default on OS X

### ISSUE THREAD

**Issue by LukasReschke** [DanielThomas/ec2gaming#4]
Realpath as called at https://github.com/DanielThomas/ec2gaming/blob/4de1e57710627ee00e9c913f7967bc1664201316/scripts/ec2gaming-vpnup.sh#L6 isn't installed by default on OS X. 

I'd thus recommend to add `coreutils` to the `brew install` statement on https://github.com/DanielThomas/ec2gaming/wiki/First-time-configuration

**Comment by DanielThomas** [comment]
Done, thanks @LukasReschke.

**Comment by LukasReschke** [comment]
Thank you! Awesome scripts btw. :)

As a side note: I had to adjust the scripts to use ZeroTier instead of Tunnelblick since my synchronous 1GBit connection somehow only got 1Mb/s via OpenVPN while ZeroTier got me a 30Mb/s. This made it kinda unusable via OpenVPN.

Is this a known issue? Anyhow, it works fine now :)
