### ISSUE TITLE
InvalidLocationConstraint for S3 bucket creation

### ISSUE THREAD

**Issue by adamyala** [DanielThomas/ec2gaming#9]
I ran `ec2gaming start` and got this error because I specified the region `us-east-1` in my `aws configure`.
```
Getting lowest g2.2xlarge bid... 0.119400 in us-east-1c
Setting price for spot instance at .219400 (0.10 higher than lowest spot price)
Looking for the ec2gaming AMI... not found. Going into bootstrap mode... ami-017dbf6a
Looking for security groups... not found. Creating security group... sg-c5f63fb8
Looking for S3 bucket... not found. Creating...
An error occurred (InvalidLocationConstraint) when calling the CreateBucket operation: The specified location-constraint is not valid
```

**Comment by DanielThomas** [comment]
Must be you need to omit the constraint for the legacy regions - will test and fix when I have a moment.

**Comment by erkserkserks** [comment]
I ran into this problem with my region us-east-1. It looks like this region is a special case: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html
